id = "zed-dreammaker-langserver"
name = "DreamMaker Language Server"
version = "0.1.2"
schema_version = 1
authors = ["mcbalaam"]
description = "DreamMaker language support for BYOND now in Zed!"

[grammars.dreammaker]
repository = "https://github.com/mcbalaam/dm-tree-sitter"
commit = "1ea303c5ca4492522d6978f21b5e7b705dabc1a4"

[language_servers.dm-langserver]
name = "DreamMaker Language Server"
languages = ["DreamMaker"]
